'📦 dependencies':
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'bun.lockb', '**/package.json']

'🎨 ui':
  - changed-files:
    - any-glob-to-any-file: ['packages/next-ui/**/*', '**/components/**/*']

'🔧 api':
  - changed-files:
    - any-glob-to-any-file: ['packages/api/**/*', 'apps/server/**/*']

'🗄️ database':
  - changed-files:
    - any-glob-to-any-file: ['packages/db/**/*', '**/prisma/**/*']

'📝 documentation':
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

'⚙️ configuration':
  - changed-files:
    - any-glob-to-any-file: ['**/*.config.*', '**/.github/**/*', '**/turbo.json', "**/.husky/**/*"]