/** biome-ignore-all assist/source/organizeImports: file auto-generated by generate:module */
import {
	CreateMemberInputSchema,
	CreateMemberOutputSchema,
	UpdateMemberInputSchema,
	UpdateMemberOutputSchema,
	FindOneMemberInputSchema,
	FindOneMemberOutputSchema,
	FindManyMemberInputSchema,
	FindManyMemberOutputSchema,
	DeleteMemberInputSchema,
	DeleteMemberOutputSchema,
} from "@vakansia/schemas";
import {
	createMember,
	updateMember,
	findOneMember,
	findManyMember,
	deleteMember,
} from "./services";
import { publicProcedure } from "../../procedures";

export const memberRouter = {
	create: publicProcedure
		.input(CreateMemberInputSchema)
		.output(CreateMemberOutputSchema)
		.handler(async ({ input }) => await createMember(input)),
	update: publicProcedure
		.input(UpdateMemberInputSchema)
		.output(UpdateMemberOutputSchema)
		.handler(async ({ input }) => await updateMember(input)),
	findOne: publicProcedure
		.input(FindOneMemberInputSchema)
		.output(FindOneMemberOutputSchema)
		.handler(async ({ input }) => await findOneMember(input)),
	findMany: publicProcedure
		.input(FindManyMemberInputSchema)
		.output(FindManyMemberOutputSchema)
		.handler(async ({ input }) => await findManyMember(input)),
	delete: publicProcedure
		.input(DeleteMemberInputSchema)
		.output(DeleteMemberOutputSchema)
		.handler(async ({ input }) => await deleteMember(input)),
};
