#!/bin/sh

echo "Build ignored..."

# Build all packages
# bun run build

# if [ $? -ne 0 ]; then
#   echo "Build failed. Please fix the issues and try again."
#   exit 1
# fi

# echo "Build completed successfully."
# exit 0
