name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    env:
      # Dummy url 
      DATABASE_URL: "postgresql://user:password@locahost:5432/vakansia"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile
        timeout-minutes: 3

      - name: Generate prisma
        run: bun run db:generate
        timeout-minutes: 3

      - name: Type check
        run: bun run check-types
        timeout-minutes: 5

      - name: Lint
        run: bun run check
        timeout-minutes: 3

      - name: Build
        run: bun run build
        timeout-minutes: 5