name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *' # Daily

jobs:
  stale:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Close stale issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 14 days with no activity.'
          close-issue-message: 'Closing due to inactivity.'
          close-pr-message: 'Closing due to inactivity.'
          days-before-stale: 30
          days-before-close: 7
          days-before-pr-stale: 14
          days-before-pr-close: 7
